services:
  localstack:
    image: localstack/localstack:3
    container_name: localstack
    environment:
      - SERVICES=s3,lambda,dynamodb
      - DEBUG=1
    ports:
      - "4566:4566"
      - "4571:4571"
    volumes:
      - "./docker-entrypoint-initaws.d:/etc/localstack/init/ready.d"
      - "/var/run/docker.sock:/var/run/docker.sock"